### ISSUE TITLE
Information about quaternion definition

### ISSUE THREAD

**Issue by antbre** [PX4/px4_msgs#33]
In many of the message definitions quaternions are only arrays of floats with no information about use of convention. A comment specifying the use of the hamilton convention could be very useful. E.g. in [`vehicle_odometry.msg`](https://github.com/PX4/px4_msgs/blob/0b282683b784c2c2d187b6e7cee8336a47d8d7a1/msg/VehicleOdometry.msg) something like:  

  ```
float32[3] position         # Position in meters. Frame of reference defined by local_frame. NaN if invalid/unknown
float32[4] q                # Quaternion rotation from FRD body frame to reference frame. First value NaN if invalid/unknown Order: [w x y z]
 ```
 
could help a lot of new users.

**Comment by beniaminopozzan** [comment]
@antbre , the messages in this repo are a copy of these ones: https://github.com/PX4/PX4-Autopilot/tree/main/msg
Please raise an issue there if you want more details in the message definitions.
